gsap.fromTo(
    ".box3",{
        y:200,
        opacity:0
    },
    {
        opacity:1,
        y:-200,
        duration:5,
        ease:"linear",
        borderRadius:0,
        repeat:-1,
        yoyo:true,
    }
)